CREATE TABLE KHOAHOC
(
    MAKH VARCHAR(10) PRIMARY KEY,
    TENKH VARCHAR(50) NOT NULL,
    NGAYBD DATE NOT NULL,
    NGAYKT DATE NOT NULL,
    CHECK (NGAYBD < NGAYKT)
)

CREATE TABLE CHUONGTRINH
(
    MACT VARCHAR(10) PRIMARY KEY,
    TENCT VARCHAR(50) NOT NULL
)

CREATE TABLE LOAILOP
(
    MALOAI VARCHAR(10) PRIMARY KEY,
    MACT VARCHAR(10) NOT NULL,
    TENLOAI VARCHAR(50) NOT NULL,
    FOREIGN KEY (MACT) REFERENCES CHUONGTRINH(MACT)
)

CREATE TABLE LOP
(
    MALOP VARCHAR(10) PRIMARY KEY,
    MALOAI VARCHAR(10) NOT NULL,
    TENLOP VARCHAR(50) NOT NULL,
    SISO INT NOT NULL,
    MAKH VARCHAR(10) NOT NULL,
    FOREIGN KEY (MAKH) REFERENCES KHOAHOC(MAKH),
    FOREIGN KEY (MALOAI) REFERENCES LOAILOP(MALOAI),
    CHECK (SISO > 12)
)

CREATE TABLE HOCVIEN
(
    MAHV VARCHAR(10) PRIMARY KEY,
    TENHV VARCHAR(50) NOT NULL,
    GIOITINH INTEGER NOT NULL,
    NGAYSINH DATE NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    DIACHI VARCHAR(100) NOT NULL,
    CHECK (GIOITINH IN (1, 0))
)

CREATE TABLE PHIEUTHU
(
    SOPT VARCHAR(10) PRIMARY KEY,
    MAHV VARCHAR(10) NOT NULL,
    MALOP VARCHAR(10) NOT NULL,
    NGAYLAPPHIEU DATE NOT NULL,
    THANHTIEN DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
    FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
    CHECK (THANHTIEN > 0)
)

CREATE TABLE MONHOC
(
    MAMH VARCHAR(10) PRIMARY KEY,
    TENMH VARCHAR(50) NOT NULL
)

CREATE TABLE DIEM
(
    MAMH VARCHAR(10) NOT NULL,
    MAHV VARCHAR(10) NOT NULL,
    MALOP VARCHAR(10) NOT NULL,
    DIEM DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (MAMH, MAHV, MALOP),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
    FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
    FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
    CHECK (DIEM >= 0 AND DIEM <= 10)
)