-- INTELLISENSE PURPOSE --
CREATE TABLE CGTRINH
(
    STT_CTR int NOT NULL ,
    TEN_CTR varchar (20) NULL ,
    DIACHI_CTR varchar (20) NULL ,
    TINH_THANH varchar (15) NULL ,
    KINH_PHI int NULL ,
    TEN_CHU varchar (20) NULL ,
    TEN_THAU varchar (20) NULL ,
    NGAY_BD date NULL
)
;


CREATE TABLE CHUNHAN
(
    TEN_CHU varchar (20) NOT NULL ,
    DCHI_CHU varchar (20) NULL
)
;


CREATE TABLE CHUTHAU
(
    TEN_THAU varchar (20) NOT NULL ,
    TEL char (7) NULL ,
    DCHI_THAU varchar (20) NULL
)
;


CREATE TABLE CONGNHAN
(
    HOTEN_CN varchar (20) NOT NULL ,
    NAMS_CN int NULL ,
    NAM_VAO_N int NULL ,
    CH_MON varchar (10) NULL
)
;


CREATE TABLE KTRUCSU
(
    HOTEN_KTS varchar (20) NOT NULL ,
    NAMS_KTS int NULL ,
    PHAI char (2) NULL ,
    NOI_TN varchar (15) NULL ,
    DCHI_LL_KTS varchar (30) NULL
)
;


CREATE TABLE THAMGIA
(
    HOTEN_CN varchar (20) NOT NULL ,
    STT_CTR int NOT NULL ,
    NGAY_TGIA date NULL ,
    SO_NGAY int NULL
)
;


CREATE TABLE THIETKE
(
    HOTEN_KTS varchar (20) NOT NULL ,
    STT_CTR int NOT NULL ,
    THU_LAO int NULL
)
;


ALTER TABLE  CGTRINH ADD 
	CONSTRAINT PK_CGTRINH PRIMARY KEY  	(STT_CTR	)  ;


ALTER TABLE  CHUNHAN ADD 
	CONSTRAINT PK_CHUNHAN PRIMARY KEY  (	TEN_CHU	)  ;


ALTER TABLE  CHUTHAU ADD 
	CONSTRAINT PK_CHUTHAU PRIMARY KEY  (	TEN_THAU	)  ;


ALTER TABLE  CONGNHAN ADD 
	CONSTRAINT PK_CONGNHAN PRIMARY KEY  (	HOTEN_CN	)  ;


ALTER TABLE  KTRUCSU ADD 
	CONSTRAINT PK_KTRUCSU PRIMARY KEY  	(	HOTEN_KTS	)  ;


ALTER TABLE  THAMGIA ADD 
	CONSTRAINT PK_THAMGIA PRIMARY KEY  	(	HOTEN_CN,	STT_CTR	)  ;


ALTER TABLE  THIETKE ADD 
	CONSTRAINT PK_THIETKE PRIMARY KEY  	(	HOTEN_KTS,	STT_CTR	)  ;


ALTER TABLE  CGTRINH ADD 
	CONSTRAINT FK_CGTRINH_CHUNHAN FOREIGN KEY 	(	TEN_CHU	) REFERENCES  CHUNHAN (	TEN_CHU	);

ALTER TABLE  CGTRINH ADD 
	CONSTRAINT FK_CGTRINH_CHUTHAU FOREIGN KEY 
	(	TEN_THAU	) REFERENCES  CHUTHAU (	TEN_THAU	);


ALTER TABLE  THAMGIA ADD 
	CONSTRAINT FK_THAMGIA_CGTRINH FOREIGN KEY 
	(		STT_CTR	) REFERENCES  CGTRINH (		STT_CTR	);

ALTER TABLE  THAMGIA ADD 
	CONSTRAINT FK_THAMGIA_CONGNHAN FOREIGN KEY 
	(		HOTEN_CN	) REFERENCES  CONGNHAN (		HOTEN_CN	);


ALTER TABLE  THIETKE ADD 
	CONSTRAINT FK_THIETKE_CGTRINH FOREIGN KEY 	(STT_CTR) REFERENCES  CGTRINH (	STT_CTR	);

ALTER TABLE  THIETKE ADD 
	CONSTRAINT FK_THIETKE_KTRUCSU FOREIGN KEY 
	(	HOTEN_KTS	) REFERENCES  KTRUCSU (	HOTEN_KTS );
-- INTELLISENSE PURPOSE --

-- 3
SELECT *
FROM KTRUCSU
WHERE HOTEN_KTS LIKE 'le%' AND NAMS_KTS = 1956;

-- 4
SELECT TEN_CTR
FROM CGTRINH
WHERE NGAY_BD BETWEEN '1994-09-01' AND '1994-10-01';

-- 5
SELECT TEN_CTR, DIACHI_CTR
FROM CGTRINH
WHERE TEN_THAU = 'cty xd so 6';

-- 6
SELECT _chuThau.TEN_THAU, _chuThau.DCHI_THAU
FROM CHUTHAU _chuThau
    JOIN CGTRINH _cgTrinh ON _chuThau.TEN_THAU = _cgTrinh.TEN_THAU
    JOIN THIETKE _thietKe ON _thietKe.STT_CTR = _CgTrinh.STT_CTR
WHERE _cgTrinh.TINH_THANH = 'can tho' AND _thietKe.HOTEN_KTS = 'le kim dung';

-- 7
SELECT DISTINCT _kTrucSu.NOI_TN
FROM KTRUCSU _kTrucSu
    JOIN THIETKE _thietKe ON _kTrucSu.HOTEN_KTS = _thietKe.HOTEN_KTS
    JOIN CGTRINH _cgTrinh ON _thietKe.STT_CTR = _cgTrinh.STT_CTR
WHERE _cgTrinh.TINH_THANH = 'can tho' AND _cgTrinh.TEN_CTR = 'khach san quoc te';

-- 8
SELECT _congNhan.HOTEN_CN, _congNhan.NAMS_CN, _congNhan.NAM_VAO_N
FROM CONGNHAN _congNhan
    JOIN THAMGIA _thamGia ON _congNhan.HOTEN_CN = _thamGia.HOTEN_CN
    JOIN CGTRINH _cgTrinh ON _cgTrinh.STT_CTR = _thamGia.STT_CTR
WHERE _congNhan.CH_MON IN ('han', 'dien') AND _cgTrinh.TEN_THAU = 'le van son';

-- 9
SELECT _congNhan.*
FROM CONGNHAN _congNhan
    JOIN THAMGIA _thamGia ON _congNhan.HOTEN_CN = _thamGia.HOTEN_CN
    JOIN CGTRINH _cgTrinh ON _cgTrinh.STT_CTR = _thamGia.STT_CTR
WHERE _cgTrinh.TINH_THANH = 'can tho'
    AND _cgTrinh.TEN_CTR = 'khach san quoc te'
    AND _thamGia.NGAY_TGIA BETWEEN '1994-12-15' AND '1994-12-31';

-- 10
SELECT _kTrucSu.HOTEN_KTS, _kTrucSu.NAMS_KTS
FROM KTRUCSU _kTrucSu
    JOIN THIETKE _thietKe ON _kTrucSu.HOTEN_KTS = _thietKe.HOTEN_KTS
    JOIN CGTRINH _cgTrinh ON _cgTrinh.STT_CTR = _thietKe.STT_CTR
WHERE _kTrucSu.NOI_TN = 'tp hcm' AND _cgTrinh.KINH_PHI > 400;

-- 11
SELECT DISTINCT _congNhan.HOTEN_CN, _congNhan.CH_MON
FROM CONGNHAN _congNhan
    JOIN THAMGIA _thamGia ON _congNhan.HOTEN_CN = _thamGia.HOTEN_CN
    JOIN CGTRINH _cgTrinh ON _cgTrinh.STT_CTR = _thamGia.STT_CTR
    JOIN THIETKE _thietKe ON _thietKe.STT_CTR = _cgTrinh.STT_CTR
WHERE _thietKe.HOTEN_KTS = 'le thanh tung';

-- 12
SELECT TEN_CTR
FROM CGTRINH
WHERE KINH_PHI = (
    SELECT MAX(KINH_PHI)
FROM CGTRINH
);

-- 13
SELECT HOTEN_KTS
FROM KTRUCSU
WHERE YEAR(NAMS_KTS) = (
    SELECT MAX(YEAR(NAMS_KTS))
FROM KTRUCSU
);

-- 14
SELECT TEN_THAU, SUM(KINH_PHI) AS TONG_KINH_PHI
FROM CGTRINH
GROUP BY TEN_THAU;

-- 15
SELECT _chuThau.TEN_THAU, _chuThau.DCHI_THAU
FROM CHUTHAU _chuThau
    JOIN CGTRINH _cgTrinh ON _chuThau.TEN_THAU = _cgTrinh.TEN_THAU
WHERE _cgTrinh.KINH_PHI = (
    SELECT MIN(KINH_PHI)
FROM CGTRINH
);

-- 16
SELECT HOTEN_KTS
FROM THIETKE
GROUP BY HOTEN_KTS
HAVING SUM(THU_LAO) > 25;

-- 17
SELECT COUNT(*)
FROM (
    SELECT HOTEN_KTS
    FROM THIETKE
    GROUP BY HOTEN_KTS
    HAVING SUM(THU_LAO) > 25
)  AS SO_LUONG_KTS;

-- 18
SELECT HOTEN_KTS, SUM(STT_CTR) AS SO_LUONG_CTR
FROM THIETKE
GROUP BY HOTEN_KTS;

-- 19
SELECT _cgTrinh.TEN_CTR, COUNT(_thamGia.HOTEN_CN) AS SO_LUONG_CN
FROM CGTRINH _cgTrinh
    LEFT JOIN THAMGIA _thamGia ON _cgTrinh.STT_CTR = _thamGia.STT_CTR
GROUP BY _cgTrinh.STT_CTR, _cgTrinh.TEN_CTR;

--20
SELECT _cgTrinh.TEN_CTR, _cgTrinh.DIACHI_CTR
FROM CGTRINH _cgTrinh
    JOIN (
    SELECT STT_CTR, COUNT(HOTEN_CN) AS SO_LUONG_CN
    FROM THAMGIA
    GROUP BY STT_CTR
) _soLuongCn ON _cgTrinh.STT_CTR = _soLuongCn.STT_CTR
WHERE _soLuongCn.SO_LUONG_CN = (
    SELECT MAX(SO_LUONG_CN)
FROM (
    SELECT COUNT(HOTEN_CN) AS SO_LUONG_CN
    FROM THAMGIA
    GROUP BY STT_CTR
    ) SO_LUONG_CN_MAX
);

-- 21
SELECT TINH_THANH, AVG(KINH_PHI) AS KINH_PHI
FROM CGTRINH
GROUP BY TINH_THANH;

-- 22
SELECT _cgTrinh.TEN_CTR, _cgTrinh.DIACHI_CTR
FROM CGTRINH _cgTrinh
    JOIN THAMGIA _thamGia ON _cgTrinh.STT_CTR = _thamGia.STT_CTR
WHERE _thamGia.HOTEN_CN = 'nguyen hong van'
    AND '1994-12-18' BETWEEN _thamGia.NGAY_TGIA AND DATEADD(day, _thamGia.SO_NGAY, _thamGia.NGAY_TGIA);

-- 23
    SELECT _thietKe.HOTEN_KTS
    FROM THIETKE _thietKe
        JOIN CGTRINH _cgTrinh ON _cgTrinh.STT_CTR = _thietKe.STT_CTR
    WHERE _cgTrinh.TEN_THAU = 'phong dich vu so xd'
INTERSECT
    SELECT _thietKe.HOTEN_KTS
    FROM THIETKE _thietKe
        JOIN CGTRINH _cgTrinh ON _cgTrinh.STT_CTR = _thietKe.STT_CTR
    WHERE _cgTrinh.TEN_THAU = 'cty xd so 6';

-- 24
    SELECT _thietKe.HOTEN_KTS
    FROM THIETKE _thietKe
        JOIN CGTRINH _cgTrinh ON _cgTrinh.STT_CTR = _thietKe.STT_CTR
    WHERE _cgTrinh.TINH_THANH = 'can tho'
EXCEPT
    SELECT _thietKe.HOTEN_KTS
    FROM THIETKE _thietKe
        JOIN CGTRINH _cgTrinh ON _cgTrinh.STT_CTR = _thietKe.STT_CTR
    WHERE _cgTrinh.TINH_THANH = 'vinh long'

-- 25
SELECT DISTINCT TEN_THAU
FROM CGTRINH
WHERE KINH_PHI > (
    SELECT MAX(KINH_PHI)
FROM CGTRINH
WHERE TEN_THAU = 'phong dich vu so xd'
);

-- 26
SELECT HOTEN_KTS
FROM THIETKE
WHERE THU_LAO < (
    SELECT AVG(THU_LAO)
FROM THIETKE
);

-- 27
SELECT HOTEN_CN, SUM(SO_NGAY)
FROM THAMGIA
GROUP BY HOTEN_CN
HAVING SUM(SO_NGAY) > 
(
    SELECT SUM(SO_NGAY)
FROM THAMGIA
WHERE HOTEN_CN = 'nguyen hong van'
);

-- 28
SELECT HOTEN_CN, COUNT(*)
FROM THAMGIA
GROUP BY HOTEN_CN HAVING COUNT(*) = (
    SELECT COUNT(*)
    FROM CGTRINH
)

-- 29
SELECT DISTINCT HOTEN_CN
FROM THAMGIA
WHERE STT_CTR IN (
    SELECT STT_CTR
    FROM THAMGIA
    WHERE HOTEN_CN = 'nguyen hong van'
);

--30
SELECT c1.TEN_THAU, c2.TEN_THAU
FROM CGTRINH c1, CGTRINH c2
WHERE c1.TINH_THANH = c2.TINH_THANH
    AND c1.TEN_THAU > c2.TEN_THAU;

-- 31
SELECT t1.HOTEN_CN, t2.HOTEN_CN
FROM THAMGIA t1 JOIN THAMGIA t2 ON t1.STT_CTR = t2.STT_CTR
WHERE t1.HOTEN_CN < t2.HOTEN_CN
GROUP BY t1.HOTEN_CN, t2.HOTEN_CN HAVING COUNT(*) > 1
