CREATE TABLE KHOAHOC (
    MAKH CHAR(4) PRIMARY KEY,
    TENKH NVARCHAR(30) NOT NULL,
    NGAYBD DATE, 
    NGAYKT DATE,
    CHECK(NGAYKT>NGAYBD)
    );

CREATE TABLE  CHUONGTRINH (
    MACT CHAR(5) PRIMARY KEY,
    TENCT NVARCHAR(50) NOT NULL );
    
CREATE TABLE LOAILOP (
    MALOAI CHAR(5) PRIMARY KEY, 
    MACT CHAR(5) NOT NULL REFERENCES CHUONGTRINH(MACT), 
    TENLOAI NVARCHAR(50) NOT NULL);

CREATE TABLE LOP (
    MALOP CHAR(4) PRIMARY KEY, 
    MALOAI  CHAR(5) NOT NULL REFERENCES LOAILOP(MALOAI), 
    TENLOP NVARCHAR(50) NOT NULL, 
    SISO SMALLINT CHECK(SISO>12), 
    MAKH CHAR(4) NOT NULL,
    FOREIGN KEY(MAKH) REFERENCES KHOAHOC(MAKH)
    );

CREATE TABLE HOCVIEN (
    MAHV CHAR(6) PRIMARY KEY,
    TENHV NVARCHAR(50) NOT NULL,
    GIOITINH NCHAR(4) CHECK(GIOITINH IN ('Nam', 'Nữ', 'Khác')),
    NGAYSINH DATE,
    SDT VARCHAR(15),
    DIACHI NVARCHAR(100)
);

CREATE TABLE PHIEUTHU (
    SOPT CHAR(6) PRIMARY KEY,
    MAHV CHAR(6) NOT NULL REFERENCES HOCVIEN(MAHV),
    MALOP CHAR(4) NOT NULL REFERENCES LOP(MALOP),
    NGAYLAPPHIEU DATE,
    THANHTIEN NUMERIC(10,2)
);

CREATE TABLE MONHOC (
    MAMH CHAR(5) PRIMARY KEY,
    TENMH NVARCHAR(50) NOT NULL
);

CREATE TABLE DIEM (
    MAMH CHAR(5) NOT NULL REFERENCES MONHOC(MAMH),
    MAHV CHAR(6) NOT NULL REFERENCES HOCVIEN(MAHV),
    MALOP CHAR(4) NOT NULL REFERENCES LOP(MALOP),
    DIEM NUMERIC(3,1) CHECK(DIEM >= 0 AND DIEM <= 10),
    PRIMARY KEY (MAMH, MAHV, MALOP)
);

-- DROP TABLE IF EXISTS KHOAHOC;
-- DROP TABLE IF EXISTS CHUONGTRINH;
-- DROP TABLE IF EXISTS LOAILOP;
-- DROP TABLE IF EXISTS LOP;
-- DROP TABLE IF EXISTS HOCVIEN;
-- DROP TABLE IF EXISTS PHIEUTHU;
-- DROP TABLE IF EXISTS MONHOC;
-- DROP TABLE IF EXISTS DIEM;