--Q1
SELECT * FROM KHOAHOC;
SELECT * FROM CHUONGTRINH;
SELECT * FROM LOAILOP;
SELECT * FROM LOP;

--Q2
SELECT * FROM HOCVIEN WHERE GIOITINH = 'Nam';

--Q3
SELECT * FROM HOCVIEN WHERE DIACHI = 'Cần Thơ';

--Q4
SELECT * FROM LOP WHERE MAKH = 'K001';

--Q5
SELECT * FROM HOCVIEN
WHERE MAHV IN (
    SELECT MAHV FROM PHIEUTHU
    WHERE MALOP IN (
        SELECT MALOP FROM LOP
        WHERE MAKH = 'K001'
    )
)

--Q6
SELECT * FROM HOCVIEN WHERE TENHV LIKE '%Đỗ%';

--Q7
SELECT * FROM HOCVIEN WHERE YEAR(NGAYSINH) = 2000;

--Q8
SELECT * FROM HOCVIEN WHERE(
    YEAR(NGAYSINH) = 2000 AND MONTH(NGAYSINH) = 12
);

--Q9
SELECT * FROM HOCVIEN WHERE(
    YEAR (NGAYSINH) >= 1998 AND YEAR(NGAYSINH) <= 2000
)

--Q10
SELECT * FROM PHIEUTHU WHERE NGAYLAPPHIEU >= '2021-06-05' AND NGAYLAPPHIEU <= '2021-06-10';

--Q11
SELECT * FROM LOP WHERE(
    TENLOP LIKE 'Lớp 1%' AND MALOAI = (
        SELECT MALOAI FROM LOAILOP
        WHERE TENLOAI = 'Tiếng Anh căn bản'
    )
)

--Q12
SELECT * FROM LOP WHERE MALOAI IN (
    SELECT MALOAI FROM LOAILOP
    WHERE TENLOAI LIKE 'Tiếng Anh Tổng Quát%'
)

--Q13
SELECT * FROM PHIEUTHU WHERE MALOP IN (
    SELECT MALOP FROM LOP
    WHERE TENLOP LIKE 'Lớp 1%' AND MALOAI IN (
        SELECT MALOAI FROM LOAILOP
        WHERE TENLOAI LIKE 'Tiếng Anh A1%'
    )
)

--Q14
SELECT h.TENHV, m.TENMH, d.DIEM
FROM HOCVIEN h
JOIN DIEM d ON h.MAHV = d.MAHV
JOIN MONHOC m ON m.MAMH = d.MAMH
WHERE d.MALOP IN (
    SELECT MALOP
    FROM LOP
    WHERE MAKH IN (
        SELECT MAKH
        FROM KHOAHOC
        WHERE TENKH = 'Khóa 1'
    )
);

--Q15
SELECT COUNT(*) AS SoLuongHocVien
FROM HOCVIEN

--Q16
SELECT COUNT(*) AS SoLuongLop FROM LOP
WHERE TENLOP LIKE 'Lớp 1%' AND MALOAI IN (
    SELECT MALOAI FROM LOAILOP
    WHERE TENLOAI LIKE 'Tiếng Anh căn bản%'
);

--Q17
SELECT SUM(THANHTIEN) AS TongDoanhThu FROM PHIEUTHU
WHERE MALOP IN (
    SELECT MALOP FROM LOP
    WHERE TENLOP LIKE 'Lớp 1%' AND MALOAI IN (
        SELECT MALOAI FROM LOAILOP
        WHERE TENLOAI LIKE 'Tiếng Anh căn bản%'
    )
);

--Q18
SELECT SUM(THANHTIEN) AS DoanhThuKhóa1 FROM PHIEUTHU
WHERE MALOP IN (
    SELECT MALOP FROM LOP
    WHERE MAKH = (
        SELECT MAKH FROM KHOAHOC
        WHERE TENKH = 'Khóa 1'
    )
);

--Q19 (I don't have the correct data)
--Q20
SELECT MAX(DIEM) AS DiemCaoNhat FROM DIEM;